# 1. nekomisystems.com
server {
    listen 8080;
    server_name nekomisystems.com localhost 127.0.0.1;

    root /usr/share/nginx/html; # Raíz de dist/
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets compartidos desde la raíz de dist/
    location /logos/ {
        alias /usr/share/nginx/html/logos/;
        try_files $uri $uri/ =404;
    }

    location /wallpapers/ {
        alias /usr/share/nginx/html/wallpapers/;
        try_files $uri $uri/ =404;
    }
}

# Subdominio DEV
server {
    listen 8080;
    server_name dev.nekomisystems.com dev.localhost;

    root /usr/share/nginx/html/dev;
    index index.html;

    location = /favicon.ico {
        alias /usr/share/nginx/html/logos/nekomi_icon.png;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /logos/ {
        alias /usr/share/nginx/html/logos/;
    }

    location /wallpapers/ {
        alias /usr/share/nginx/html/wallpapers/;
    }

    location /cv.pdf{
        alias /app/files/cv/cv_david_espanol.pdf;
    }

    location /resume.pdf{
        alias /app/files/cv/cv_david_ingles.pdf;
    }

    location /cv_spanish{
        alias /app/files/cv/cv_david_espanol.pdf;
        add_header Content-Type application/pdf;
        #leerlo en pestaña
        add_header Content-Disposition 'inline; filename="CV_David_Zepeda_Espanol.pdf"';
        #descargar: Content-Disposition 'attachment
    }

    location /cv_english{
        alias /app/files/cv/cv_david_ingles.pdf;
        add_header Content-Type application/pdf;
        #leerlo en pestaña
        add_header Content-Disposition 'inline; filename="Resume_David_Zepeda_English.pdf"';
        #descargar: Content-Disposition 'attachment
    }
}

# 2. Subdominio PORTFOLIO
server {
    listen 8080;
    server_name portfolio.nekomisystems.com portfolio.localhost;

    root /usr/share/nginx/html/portfolio;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirecciona las peticiones de /assets a la raíz compartida de dist/
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }

    location /desktopmiku/ {
        alias /usr/share/nginx/html/desktopmiku/;
    }

    location /dflip/ {
        alias /usr/share/nginx/html/dflip/;
    }

    location /discord/ {
        alias /usr/share/nginx/html/discord/;
    }

    location /games/ {
        alias /usr/share/nginx/html/games/;
    }

    location /mspaint/ {
        alias /usr/share/nginx/html/mspaint/;
    }

    location /selection/ {
        alias /usr/share/nginx/html/selection/;
    }

    location /tetris/ {
        alias /usr/share/nginx/html/tetris/;
    }

    location /logos/ {
        alias /usr/share/nginx/html/logos/;
    }

    location /wallpapers/ {
        alias /usr/share/nginx/html/wallpapers/;
    }

    location /frost-os/ {
        alias /usr/share/nginx/html/frost-os/;
        index index.html;
        try_files $uri $uri/ /frost-os/index.html;
    }

    location /mikurig/ {
        alias /usr/share/nginx/html/mikurig/;
        index index.html;
        try_files $uri $uri/ /mikurig/index.html;
    }

    location /manga_reader/ {
        alias /usr/share/nginx/html/manga_reader/;
        index index.html;
        try_files $uri $uri/ /manga_reader/index.html;
    }

    location /bibootaxgame/ {
        alias /usr/share/nginx/html/bibootaxgame/;
        index index.html;
        try_files $uri $uri/ /bibootaxgame/index.html;
    }

    location /the-dropper/ {
        alias /usr/share/nginx/html/the-dropper/;
        index index.html;
        try_files $uri $uri/ /the-dropper/index.html;
    }

    location /zombie-game/ {
        alias /usr/share/nginx/html/zombie-game/;
        index index.html;
        try_files $uri $uri/ /zombie-game/index.html;
    }
}
